[project]
name = "langchainexplore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepagents>=0.7.13",
    "httpx>=0.28.1",
    "langchain-core>=1.6.1",
    "langchain-google-genai>=4.4.0",
    "markdownify>=1.2.3",
    "python-dotenv>=1.1.0",
    "tavily-python>=0.8.1",
]

[tool.uv.workspace]
members = [
    "deep-research-agent",
]
